[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss18"

    [buildPlans.IosevkaCustom.variants.design]
    one = "base-long-top-serif"
    two = "curly-neck-serifless"
    three = "two-arcs"
    four = "closed-serifless"
    five = "upright-flat-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "reverse-slashed"
    capital-a = "straight-serifless"
    capital-b = "standard-serifless"
    capital-d = "more-rounded-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-j = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-q = "straight"
    capital-r = "straight-serifless"
    capital-t = "serifless"
    capital-w = "straight-serifless"
    a = "double-storey-serifless"
    b = "toothed-serifless"
    f = "flat-hook-serifed"
    g = "double-storey"
    i = "serifed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "hookless-serifed"
    t = "flat-hook-short-neck2"
    u = "toothed-serifless"
    y = "straight-turn-serifless"
    lower-lambda = "tailed-turn"
    braille-dot = "square"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "low"
    ascii-grave = "raised-turn-comma"
    ascii-single-quote = "raised-comma"
    paren = "flat-arc"
    brace = "curly"
    guillemet = "curly"
    number-sign = "upright"
    ampersand = "closed"
    at = "compact"
    dollar = "slanted-open"
    cent = "open-cap"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "smooth"
    decorative-angle-brackets = "middle"
    lig-ltgteq = "slanted"
    lig-neq = "vertical-dotted"
    lig-single-arrow-bar = "without-notch"

    [buildPlans.IosevkaCustom.variants.italic]
    one = "base-long-top-serif"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    four = "open-serifless"
    five = "oblique-arched-serifless"
    six = "open-contour"
    nine = "open-contour"
    zero = "oval-tall-slashed"
    capital-a = "straight-serifless"
    capital-b = "more-asymmetric-serifless"
    capital-d = "more-rounded-serifless"
    capital-j = "serifed"
    capital-k = "straight-serifless"
    capital-m = "hanging-serifless"
    capital-n = "standard-serifless"
    capital-q = "curly-tailed"
    capital-r = "straight-serifless"
    capital-t = "serifless"
    capital-w = "straight-serifless"
    a = "single-storey-tailed"
    b = "toothed-serifless"
    d = "toothed-serifless"
    e = "rounded"
    f = "flat-hook-diagonal-tailed"
    g = "single-storey-serifless"
    i = "serifed-diagonal-tailed"
    j = "diagonal-tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    l = "serifed-diagonal-tailed"
    m = "serifless"
    n = "straight-serifless"
    p = "eared-serifless"
    q = "straight-serifless"
    r = "hookless-top-serifed"
    t = "diagonal-tailed-short-neck2"
    u = "toothed-serifless"
    v = "cursive-serifed"
    w = "cursive-serifless"
    x = "cursive"
    y = "cursive-serifless"
    z = "cursive"
    braille-dot = "square"
    tilde = "low"
    asterisk = "penta-low"
    ascii-grave = "raised-turn-comma"
    ascii-single-quote = "raised-comma"
    ampersand = "closed"
    at = "compact"
    dollar = "slanted-open"
    cent = "open-cap"
    percent = "rings-continuous-slash"
    question = "smooth"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
