name: Build Custom Iosevka Fonts

on: [workflow_dispatch]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Checkout this repository to access custom build plans
        uses: actions/checkout@v5

      - name: Get the list of font families in private-build-plans.toml
        id: get-families
        shell: bash
        working-directory: get-all-families-in-private-build-plan
        run: |
          npm install
          node ./index.mjs >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.fontFamily }} font
    runs-on: ubuntu-latest
    
    needs: [setup-matrix]

    strategy:
      matrix:
        fontFamily: ${{ fromJson(needs.setup-matrix.outputs.fontFamilies) }}

    steps:
      # Setup dependencies
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install ttfautohint
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      # Checkout this repository to access custom build plans
      - uses: actions/checkout@v5
        with:
          path: customization

      # Checkout repository into `iosevka` sub directory
      - uses: actions/checkout@v5
        with:
          repository: be5invis/iosevka # You can change this to your own fork
          path: iosevka
      
      # Copy custom build plans into Iosevka build directory
      - name: Copy Custom Build Plans
        shell: bash
        run: |
          cp customization/private-build-plans.toml iosevka/private-build-plans.toml

      # Build the font
      - name: Build Font ${{ matrix.fontFamily }}
        shell: bash
        working-directory: iosevka
        run: |
          npm install
          npm run build -- ttf::${{ matrix.fontFamily }}

      # Upload build artifacts
      - name: Upload Font Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fontFamily }}-ttf
          path: iosevka/dist/${{ matrix.fontFamily }}/TTF/
